name = "qloudsound-site"
main = ".vercel/output/static/_worker.js/index.js"
account_id = "b7eb9a280f73e95d5d278026959c1a60"

compatibility_date = "2024-11-08"
compatibility_flags = ["nodejs_compat"]


[vars]
NODE_ENV = "production"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[[routes]]
pattern = "qloudsound.com/*"
custom_domain = true

[[routes]]
pattern = "www.qloudsound.com/*"
custom_domain = true